Scheator: ScheatorView.MainTablePanel.ButtonListener Class Reference
ScheatorView.MainTablePanel.ButtonListener Class Reference
Public Member Functions
void actionPerformed (ActionEvent e)
Package Functions
ButtonListener ()
Detailed Description
Definition at line 155 of file MainTablePanel.java.
Constructor & Destructor Documentation
ScheatorView.MainTablePanel.ButtonListener.ButtonListener () [package]
Definition at line 156 of file MainTablePanel.java.
{
        }
Member Function Documentation
void ScheatorView.MainTablePanel.ButtonListener.actionPerformed (ActionEvent e)
Definition at line 159 of file MainTablePanel.java.
References ScheatorView.MainTablePanel.mainTable, ScheatorView.MainTablePanel.mainTableModel, ScheatorModel.MainTableModel.moveMatch(), ScheatorModel.MainTableModel.save(), and ScheatorView.MainTablePanel.setTableEdited().
{
            if (e.getActionCommand().equals("Up")) {
                Integer row = mainTable.getSelectedRow();
                if (row > 0) {
                    mainTableModel.moveMatch(row, row - 1);
                    setTableEdited(true);
                }
            }
            else if (e.getActionCommand().equals("Down")) {
                Integer row = mainTable.getSelectedRow();
                if (row < mainTable.getRowCount()-1) {
                    mainTableModel.moveMatch(row, row + 1);
                    setTableEdited(true);
                }
            }
            else if (e.getActionCommand().equals("Save")) {
                mainTableModel.save();
            }
        }
The documentation for this class was generated from the following file:
src/ScheatorView/MainTablePanel.java