Scheator: ScheatorDb.MySqlDb Class Reference
ScheatorDb.MySqlDb Class Reference
Package Functions
MySqlDb ()
MySqlDb (String db, String user, String pw)
Package Attributes
Connection con = null
AbstractQueryEngine qe
Private Member Functions
void initDb (String db, String user, String pw)
Detailed Description
Database connector for a MySql database.
Author:
mep
Definition at line 14 of file MySqlDb.java.
Constructor & Destructor Documentation
ScheatorDb.MySqlDb.MySqlDb () [package]
Definition at line 16 of file MySqlDb.java.
References ScheatorDb.MySqlDb.initDb().
              {
        // Use default values for testing
        initDb("scheator", "root", "root");
    }
ScheatorDb.MySqlDb.MySqlDb (String db, String user, String pw) [package]
Creates connection to the database.
Parameters:
db Database name.
user User name for the db connection.
pw Password for the db connection.
Definition at line 28 of file MySqlDb.java.
References ScheatorDb.MySqlDb.initDb().
{
        initDb(db, user, pw);
    }
Member Function Documentation
void ScheatorDb.MySqlDb.initDb (String db, String user, String pw) [private]
Definition at line 32 of file MySqlDb.java.
References ScheatorDb.AbstractDb.con, and ScheatorDb.AbstractDb.qe.
Referenced by ScheatorDb.MySqlDb.MySqlDb().
{
        if (db.length() == 0) {
            db = "scheator";
        }
        String url = "jdbc:mysql://localhost/" + db;
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection(url, user, pw);
            if (!con.isClosed()) {
            }
            else {
                System.err.println("Failed to connecto to " + db);
            }
        }
        catch (Exception e) {
           System.err.println("Exception: "+ e.getMessage());
        }
        qe = new SqlQueryEngine();
    }
Member Data Documentation
Connection ScheatorDb.AbstractDb.con = null [package, inherited]
Definition at line 17 of file AbstractDb.java.
Referenced by ScheatorDb.SqlDb.initDb(), and ScheatorDb.MySqlDb.initDb().
AbstractQueryEngine ScheatorDb.AbstractDb.qe [package, inherited]
Definition at line 19 of file AbstractDb.java.
Referenced by ScheatorDb.SqlDb.initDb(), and ScheatorDb.MySqlDb.initDb().
The documentation for this class was generated from the following file:
src/ScheatorDb/MySqlDb.java