Scheator: ScheatorController.MainController Class Reference
ScheatorController.MainController Class Reference
Public Member Functions
void searchMainTable (int seasonId)
void scheduleEdited ()
void moveMatch (Integer startPos, Integer endPos)
void addModel (Object model)
void removeModel (Object model)
void addView (AbstractView view)
void removeView (AbstractView view)
void addMainFrame (MainView frame)
Static Public Attributes
static final String SERIES_LIST = "SERIES_LIST"
static final String SEASON_LIST = "SEASON_LIST"
static final String SCHEDULE_DATA = "SCHEDULE_DATA"
Package Attributes
ArrayList< AbstractView > registeredViews
MainView mainFrame
ArrayList< Object > registeredModels
Static Private Attributes
static final String MAINTABLE_MODEL_NAME = "ScheatorModel.MainTableModel"
static final String MAINTABLE_UPDATE = "update"
Detailed Description
Main application controller.
Author:
mep
Definition at line 9 of file MainController.java.
Member Function Documentation
void ScheatorController.AbstractController.addMainFrame (MainView frame) [inherited]
Definition at line 96 of file AbstractController.java.
References ScheatorController.AbstractController.mainFrame.
Referenced by ScheatorView.MainView.MainView().
{
        this.mainFrame = frame;
    }
void ScheatorController.AbstractController.addModel (Object model) [inherited]
Binds a model to this controller. Once added, the controller will listen for all model property changes and propogate them on to registered views. In addition, it is also responsible for resetting the model properties when a view changes state.
Parameters:
model The model to be added
Definition at line 41 of file AbstractController.java.
References ScheatorController.AbstractController.registeredModels.
Referenced by ScheatorModel.MainTableModel.MainTableModel(), ScheatorModel.SeasonComboBoxModel.SeasonComboBoxModel(), and ScheatorModel.SeriesComboBoxModel.SeriesComboBoxModel().
{
        registeredModels.add(model);
        if(model instanceof AbstractTableModel) {
            AbstractTableModel T = (AbstractTableModel) model;
            T.addTableModelListener(new TableModelListenerImpl());
        }
        if (model instanceof AbstractListModel) {
            AbstractListModel T = (AbstractListModel) model;
            T.addListDataListener(new ListDataListenerImpl());
        }
        if (model instanceof ItemSelectable) {
            ItemSelectable T = (ItemSelectable) model;
            T.addItemListener(new ItemListenerImpl());
        }
    }
void ScheatorController.AbstractController.addView (AbstractView view) [inherited]
Binds a view to this controller. The controller will propogate all model property changes to each view for consideration.
Parameters:
view The view to be added
Definition at line 84 of file AbstractController.java.
References ScheatorController.AbstractController.registeredViews.
Referenced by ScheatorView.MainView.initComponents(), ScheatorView.MainSearchPanel.MainSearchPanel(), and ScheatorView.MainTablePanel.MainTablePanel().
{
        registeredViews.add(view);
    }
void ScheatorController.MainController.moveMatch (Integer startPos, Integer endPos)
Definition at line 50 of file MainController.java.
Referenced by ScheatorView.MainTablePanel.moveDown(), and ScheatorView.MainTablePanel.moveUp().
{
    }
void ScheatorController.AbstractController.removeModel (Object model) [inherited]
Unbinds a model from this controller.
Parameters:
model The model to be removed
Definition at line 61 of file AbstractController.java.
References ScheatorController.AbstractController.registeredModels.
{
        registeredModels.remove(model);
        if(model instanceof AbstractTableModel) {
            AbstractTableModel T = (AbstractTableModel) model;
            T.removeTableModelListener(new TableModelListenerImpl());
        }
        if (model instanceof AbstractListModel) {
            AbstractListModel T = (AbstractListModel) model;
            T.removeListDataListener(new ListDataListenerImpl());
        }
        if (model instanceof ItemSelectable) {
            System.err.println("Item is selectable");
            ItemSelectable T = (ItemSelectable) model;
            T.addItemListener(new ItemListenerImpl());
        }
    }
void ScheatorController.AbstractController.removeView (AbstractView view) [inherited]
Unbinds a view from this controller.
Parameters:
view The view to be removed
Definition at line 92 of file AbstractController.java.
References ScheatorController.AbstractController.registeredViews.
{
        registeredViews.remove(view);
    }
void ScheatorController.MainController.scheduleEdited ()
Definition at line 46 of file MainController.java.
Referenced by ScheatorView.MainTablePanel.save().
{
    }
void ScheatorController.MainController.searchMainTable (int seasonId)
Event happened that require filling the in the main table.
Parameters:
seasonId Database id for the season to be used to fill in the table.
Definition at line 25 of file MainController.java.
References ScheatorController.MainController.MAINTABLE_MODEL_NAME, ScheatorController.MainController.MAINTABLE_UPDATE, and ScheatorController.AbstractController.registeredModels.
Referenced by ScheatorView.MainSearchPanel.search().
{
        //System.err.println("searchMainTable()");
        for (Object model: registeredModels) {
            Class c = model.getClass();
            //System.err.println("Class = " + c.getName());
            if (c.getName().equals(MAINTABLE_MODEL_NAME)) {
                System.err.println("Model found");
                Class parTypes[] = new Class[1];
                parTypes[0] = Integer.TYPE;
                try {
                    Method m = c.getMethod(MAINTABLE_UPDATE, parTypes);
                    Object argList[] = new Object[1];
                    argList[0] = new Integer(seasonId);
                    m.invoke(model, argList);
                } catch (Throwable e) {
                    //System.err.println("Fail " + e.toString());
                }
            }
        }
    }
Member Data Documentation
MainView ScheatorController.AbstractController.mainFrame [package, inherited]
Definition at line 24 of file AbstractController.java.
Referenced by ScheatorController.AbstractController.addMainFrame(), ScheatorController.AbstractController.ListDataListenerImpl.contentsChanged(), ScheatorController.AbstractController.ListDataListenerImpl.intervalAdded(), ScheatorController.AbstractController.ListDataListenerImpl.intervalRemoved(), ScheatorController.AbstractController.ItemListenerImpl.itemStateChanged(), and ScheatorController.AbstractController.TableModelListenerImpl.tableChanged().
final String ScheatorController.MainController.MAINTABLE_MODEL_NAME = "ScheatorModel.MainTableModel" [static, private]
Main table model class name.
Definition at line 16 of file MainController.java.
Referenced by ScheatorController.MainController.searchMainTable().
final String ScheatorController.MainController.MAINTABLE_UPDATE = "update" [static, private]
Method name for updating main table contents.
Definition at line 18 of file MainController.java.
Referenced by ScheatorController.MainController.searchMainTable().
ArrayList<Object> ScheatorController.AbstractController.registeredModels [package, inherited]
Definition at line 25 of file AbstractController.java.
Referenced by ScheatorController.AbstractController.AbstractController(), ScheatorController.AbstractController.addModel(), ScheatorController.AbstractController.removeModel(), and ScheatorController.MainController.searchMainTable().
ArrayList<AbstractView> ScheatorController.AbstractController.registeredViews [package, inherited]
Definition at line 23 of file AbstractController.java.
Referenced by ScheatorController.AbstractController.AbstractController(), ScheatorController.AbstractController.addView(), ScheatorController.AbstractController.ListDataListenerImpl.contentsChanged(), ScheatorController.AbstractController.ListDataListenerImpl.intervalAdded(), ScheatorController.AbstractController.ListDataListenerImpl.intervalRemoved(), ScheatorController.AbstractController.ItemListenerImpl.itemStateChanged(), ScheatorController.AbstractController.removeView(), and ScheatorController.AbstractController.TableModelListenerImpl.tableChanged().
final String ScheatorController.MainController.SCHEDULE_DATA = "SCHEDULE_DATA" [static]
Definition at line 13 of file MainController.java.
final String ScheatorController.MainController.SEASON_LIST = "SEASON_LIST" [static]
Definition at line 12 of file MainController.java.
final String ScheatorController.MainController.SERIES_LIST = "SERIES_LIST" [static]
Definition at line 11 of file MainController.java.
The documentation for this class was generated from the following file:
src/ScheatorController/MainController.java