Scheator: ScheatorDb.SqlQueryEngine Class Reference
ScheatorDb.SqlQueryEngine Class Reference
Public Member Functions
String getItems (String[] table, String[] fields, String[] idFields, String[] ids, String[] orderBy)
String addItem (String table, Object toAdd)
String updateItem (String entity, Object toUpdate, String[] idFields, String[] ids)
String deleteItems (String table, String[] idFields, String[] ids)
Package Functions
String formatValue (Field f)
Private Member Functions
String createWhereClause (String[] idFields, String[] ids)
String createOrderByClause (String[] list)
Detailed Description
A class for creating SQL queries.
Todo:
getItems() and deleteItems do not support varchar (=String) type search fields as the values should be enclosed in single quotes. This is done in addItem() but since I don't need this feature it has not been implemented.
Author:
mep
Definition at line 13 of file SqlQueryEngine.java.
Member Function Documentation
String ScheatorDb.SqlQueryEngine.addItem (String table, Object toAdd) [virtual]
Builds an SQL query string to add an item to the database.
Parameters:
table Table name.
toAdd Object to add.
Returns:
SQL query.
Implements ScheatorDb.AbstractQueryEngine.
Definition at line 69 of file SqlQueryEngine.java.
References ScheatorDb.SqlQueryEngine.formatValue().
{
        StringBuilder sb = new StringBuilder();
        StringBuilder sbFields = new StringBuilder();
        StringBuilder sbValues = new StringBuilder();
        sb.append("INSERT INTO ");
        sb.append(table);
        sb.append(" VALUES ");
        sbFields.append("(");
        sbValues.append("(");
        for (Field f: toAdd.getClass().getDeclaredFields()) {
            String fieldName = f.getName();
            if (fieldName.startsWith("field_")) {
                String type = f.getClass().getName();
                String value = new String();
                sbFields.append(fieldName);
                sbValues.append(formatValue(f));
                sbFields.append(",");
                sbValues.append(",");
            }
        }
        // Remove extra commas and add missing closing parentheses
        sb.append(sbFields.toString().substring(0, sbFields.toString().length()-1));
        sb.append(")");
        sb.append(sbValues.toString().substring(0, sbValues.toString().length()-1));
        sb.append(")");
        System.err.println("addItems returns " + sb.toString());
        return sb.toString();
    }
String ScheatorDb.SqlQueryEngine.createOrderByClause (String[] list) [private]
Creates the order by clause part of an sql query.
Parameters:
list Field list for the clause.
Returns:
String containing the ORDER BY clause.
Definition at line 191 of file SqlQueryEngine.java.
Referenced by ScheatorDb.SqlQueryEngine.getItems().
{
        StringBuilder sb = new StringBuilder();
        if (list != null) {
            sb.append("ORDER BY ");
            for (int i =0;i<list.length;i++) {
                sb.append(list[i]);
                if (i < list.length-1) {
                    sb.append(", ");
                }
            }
        }
        return sb.toString();
    }
String ScheatorDb.SqlQueryEngine.createWhereClause (String[] idFields, String[] ids) [private]
Builds the WHERE part of an SQL query.
Parameters:
idFields Fields of the query.
ids Values of the query.
Returns:
WHERE part of an SQL query.
Definition at line 170 of file SqlQueryEngine.java.
Referenced by ScheatorDb.SqlQueryEngine.deleteItems(), ScheatorDb.SqlQueryEngine.getItems(), and ScheatorDb.SqlQueryEngine.updateItem().
{
        StringBuilder sb = new StringBuilder();
        if (idFields != null && ids != null) {
            sb.append(" WHERE ");
            for(int i=0;i<idFields.length;i++) {
                sb.append(idFields[i] + " = ");
                sb.append(ids[i]);
                if (i < ids.length-1) {
                    sb.append(" AND ");
                }
            }
        }
        return sb.toString();
    }
String ScheatorDb.SqlQueryEngine.deleteItems (String table, String[] idFields, String[] ids) [virtual]
Builds an SQL query to delete items from the database.
Parameters:
table Table name. Mandatory.
idField Field names for the query. If this is null, contents of the entire table is cleared.
id Id values for the query. Must be in the same order as the fields in idField. If this is null, contents of the entire table is cleared.
Returns:
SQL query string.
Implements ScheatorDb.AbstractQueryEngine.
Definition at line 154 of file SqlQueryEngine.java.
References ScheatorDb.SqlQueryEngine.createWhereClause().
{
        StringBuilder sb = new StringBuilder();
        sb.append("DELETE FROM ");
        sb.append(table);
        sb.append(createWhereClause(idFields, ids));
        return sb.toString();
    }
String ScheatorDb.SqlQueryEngine.formatValue (Field f) [package]
Formats a value for an sql query.
This function assumes that the field type is equivalent to the field in the database. In practice this means that this field support two types of fields: string (varchar) and numeric.
A string type field will be escaped with single parenthesis (') because SQL databases expect that. Numbers are returned as-is.
If the field is null, a string containing "NULL" is returned instead.
Parameters:
f The field where the value is.
Returns:
Formatted value.
Definition at line 221 of file SqlQueryEngine.java.
Referenced by ScheatorDb.SqlQueryEngine.addItem(), and ScheatorDb.SqlQueryEngine.updateItem().
{
        String retval = null;
        String type = f.getClass().getName();
        if (type.equals("String")) {
            try {
                String value = (String)f.get(f);
                if (value != null) {
                    retval = "'" + value + "'";
                } else {
                    retval = "NULL";
                }
            } catch (Exception e) {
                System.err.println("No such field: " + e.getMessage());
            }
        } else if (type.equals("Integer")) {
            try {
                Integer value = (Integer)f.get(f);
                if (value != null) {
                    retval = String.valueOf(value);
                } else {
                    retval = "NULL";
                }
            } catch (Exception e) {
                System.err.println("No such field: " + e.getMessage());
            }
        } else {
            try {
                String value = (String) f.get(f);
                if (value != null) {
                    retval = value;
                } else {
                    retval = "NULL";
                }
            } catch (Exception e) {
                System.err.println("No such field: " + e.getMessage());
            }
        }
        return retval;
    }
String ScheatorDb.SqlQueryEngine.getItems (String[] table, String[] fields, String[] idFields, String[] ids, String[] orderBy) [virtual]
Returns an SQL query for retrieving information from a database.
Todo:
get and delete do not add escape characters for String type fields.
Parameters:
table Table names.
fields Field names. If this is null, * is used.
idFields Fields used to query the database. If this is null, every row is returned.
ids Values for the id fields. Must be in the same order as the idFields. If this is null, every row is returned.
Returns:
SQL query string.
Implements ScheatorDb.AbstractQueryEngine.
Definition at line 28 of file SqlQueryEngine.java.
References ScheatorDb.SqlQueryEngine.createOrderByClause(), and ScheatorDb.SqlQueryEngine.createWhereClause().
{
        StringBuilder sb = new StringBuilder();
        if (fields == null) {
            sb.append("SELECT * FROM ");
        } else {
            sb.append("SELECT ");
            for(int i=0;i<fields.length;i++) {
                 sb.append(fields[i]);
                 if (i < fields.length-1) {
                     sb.append(", ");
                 }
            }
            sb.append(" FROM ");
        }
        for(int i=0;i<table.length;i++) {
            sb.append(table[i]);
            if (i<table.length-1) {
                sb.append(", ");
            } else {
                sb.append(" ");
            }
        }
        sb.append(createWhereClause(idFields, ids));
        sb.append(" ");
        sb.append(createOrderByClause(orderBy));
        System.err.println("SqlQueryEngine.getItems() returns " + sb.toString());
        return sb.toString();
    }
String ScheatorDb.SqlQueryEngine.updateItem (String entity, Object toUpdate, String[] idFields, String[] ids) [virtual]
Creates an SQL query for updating a row's values in the database.
Parameters:
entity Table name.
toUpdate Fields and values to update. All of the fields will be updated, so each field must have a meaningful value!
idFields Fields used to identify the row(s).
ids Id values for id fields. Values must be in the same order as the fields.
Returns:
Implements ScheatorDb.AbstractQueryEngine.
Definition at line 114 of file SqlQueryEngine.java.
References ScheatorDb.SqlQueryEngine.createWhereClause(), and ScheatorDb.SqlQueryEngine.formatValue().
{
        StringBuilder sb = new StringBuilder();
        sb.append("UPDATE ");
        sb.append(entity);
        sb.append("SET ");
        for (Field f: toUpdate.getClass().getDeclaredFields()) {
            String fieldName = f.getName();
            if (fieldName.startsWith("field_")) {
                String type = f.getClass().getName();
                String value = new String();
                sb.append(fieldName);
                sb.append("=");
                sb.append(formatValue(f));
                sb.append(",");
            }
        }
        /* Remove last comma */
        sb.deleteCharAt(sb.toString().length()-1);
        /* Add where clause */
        sb.append(createWhereClause(idFields, ids));
        return sb.toString();
    }
The documentation for this class was generated from the following file:
src/ScheatorDb/SqlQueryEngine.java