Scheator: ScheatorView.MainView Class Reference
ScheatorView.MainView Class Reference
Public Member Functions
MainView (SingleFrameApplication app, MainController controller)
void showAboutBox ()
void createSchedule ()
void print ()
void editSeries ()
void editTeams ()
void editSchedule ()
void mainTableChanged (TableModelEvent e)
void comboBoxEvent (ListDataEvent e)
void itemStateChanged (ItemEvent e)
Private Member Functions
void initComponents ()
Private Attributes
JDialog aboutBox
javax.swing.JPanel mainPanel
javax.swing.JMenuBar menuBar
javax.swing.JProgressBar progressBar
javax.swing.JLabel statusAnimationLabel
javax.swing.JLabel statusMessageLabel
javax.swing.JPanel statusPanel
MainController controller
Detailed Description
Author:
mep
Definition at line 27 of file MainView.java.
Constructor & Destructor Documentation
ScheatorView.MainView.MainView (SingleFrameApplication app, MainController controller)
Definition at line 38 of file MainView.java.
References ScheatorController.AbstractController.addMainFrame(), and ScheatorView.MainView.initComponents().
{
        super(app);
        this.controller = controller;
        controller.addMainFrame(this);
        initComponents();
    }
Member Function Documentation
void ScheatorView.MainView.comboBoxEvent (ListDataEvent e)
Definition at line 216 of file MainView.java.
Referenced by ScheatorController.AbstractController.ListDataListenerImpl.contentsChanged(), ScheatorController.AbstractController.ListDataListenerImpl.intervalAdded(), and ScheatorController.AbstractController.ListDataListenerImpl.intervalRemoved().
{
    }
void ScheatorView.MainView.createSchedule ()
Definition at line 58 of file MainView.java.
{
    }
void ScheatorView.MainView.editSchedule ()
Definition at line 78 of file MainView.java.
{
    }
void ScheatorView.MainView.editSeries ()
Definition at line 68 of file MainView.java.
{
    }
void ScheatorView.MainView.editTeams ()
Definition at line 73 of file MainView.java.
{
    }
void ScheatorView.MainView.initComponents () [private]
Definition at line 82 of file MainView.java.
References ScheatorController.AbstractController.addView(), ScheatorView.MainView.controller, ScheatorView.MainView.mainPanel, ScheatorView.MainView.menuBar, ScheatorView.MainView.progressBar, ScheatorView.MainView.statusAnimationLabel, ScheatorView.MainView.statusMessageLabel, and ScheatorView.MainView.statusPanel.
Referenced by ScheatorView.MainView.MainView().
{
        mainPanel = new javax.swing.JPanel();
        // Menus
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem createScheduleMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem printMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu editMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem seriesMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem teamsMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenuItem scheduleMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        // Status panel
        statusPanel = new javax.swing.JPanel();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(scheator.ScheatorApp.class).getContext().getResourceMap(MainView.class);
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(scheator.ScheatorApp.class).getContext().getActionMap(MainView.class, this);
        // Panels (one split pane that includes two scroll panes)
        MainSearchPanel searchPanel = new MainSearchPanel(controller);
        MainTablePanel tablePanel = new MainTablePanel(controller);
        controller.addView(searchPanel);
        controller.addView(tablePanel);
        JSplitPane splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, searchPanel, tablePanel);
        //JPanel searchPanel = new javax.swing.JPanel();
        splitPane.setOrientation(JSplitPane.VERTICAL_SPLIT);
        splitPane.setName("splitPane");
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerLocation(50);
        //searchPanel = createSearchPanel(resourceMap, actionMap);
        splitPane.setTopComponent(searchPanel);
//        tablePanel = createTablePanel(resourceMap, actionMap);
        splitPane.setBottomComponent(tablePanel);
        //mainPanel.setSize(new Dimension(1000,1000));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.add(splitPane);
        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        // Menu bars
        menuBar.setName("menuBar"); // NOI18N
        // ----
        // File
        //
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N
        createScheduleMenuItem.setAction(actionMap.get("createSchedule"));
        createScheduleMenuItem.setName("createSchedule");
        fileMenu.add(createScheduleMenuItem);
        fileMenu.addSeparator();
        printMenuItem.setAction(actionMap.get("print"));
        printMenuItem.setName("print");
        fileMenu.add(printMenuItem);
        fileMenu.addSeparator();
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);
        menuBar.add(fileMenu);
        // ----
        // Edit
        //
        editMenu.setText(resourceMap.getString("editMenu.text"));
        editMenu.setName("editMenu");
        seriesMenuItem.setAction(actionMap.get("editSeries"));
        seriesMenuItem.setName("editSeries");
        editMenu.add(seriesMenuItem);
        teamsMenuItem.setAction(actionMap.get("editTeams"));
        teamsMenuItem.setName("editTeams");
        editMenu.add(teamsMenuItem);
        scheduleMenuItem.setAction(actionMap.get("editSchedule"));
        scheduleMenuItem.setName("editSchedule");
        editMenu.add(scheduleMenuItem);
        menuBar.add(editMenu);
        // ----
        // Help
        //
        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N
        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);
        menuBar.add(helpMenu);
        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }
void ScheatorView.MainView.itemStateChanged (ItemEvent e)
Definition at line 220 of file MainView.java.
Referenced by ScheatorController.AbstractController.ItemListenerImpl.itemStateChanged().
{
    }
void ScheatorView.MainView.mainTableChanged (TableModelEvent e)
Definition at line 213 of file MainView.java.
Referenced by ScheatorController.AbstractController.TableModelListenerImpl.tableChanged().
{
    }
void ScheatorView.MainView.print ()
Definition at line 63 of file MainView.java.
{
    }
void ScheatorView.MainView.showAboutBox ()
Definition at line 48 of file MainView.java.
References ScheatorView.MainView.aboutBox.
{
        if (aboutBox == null) {
            JFrame mainFrame = ScheatorApp.getApplication().getMainFrame();
            aboutBox = new ScheatorAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        ScheatorApp.getApplication().show(aboutBox);
    }
Member Data Documentation
JDialog ScheatorView.MainView.aboutBox [private]
Definition at line 29 of file MainView.java.
Referenced by ScheatorView.MainView.showAboutBox().
MainController ScheatorView.MainView.controller [private]
Definition at line 36 of file MainView.java.
Referenced by ScheatorView.MainView.initComponents().
javax.swing.JPanel ScheatorView.MainView.mainPanel [private]
Definition at line 30 of file MainView.java.
Referenced by ScheatorView.MainView.initComponents().
javax.swing.JMenuBar ScheatorView.MainView.menuBar [private]
Definition at line 31 of file MainView.java.
Referenced by ScheatorView.MainView.initComponents().
javax.swing.JProgressBar ScheatorView.MainView.progressBar [private]
Definition at line 32 of file MainView.java.
Referenced by ScheatorView.MainView.initComponents().
javax.swing.JLabel ScheatorView.MainView.statusAnimationLabel [private]
Definition at line 33 of file MainView.java.
Referenced by ScheatorView.MainView.initComponents().
javax.swing.JLabel ScheatorView.MainView.statusMessageLabel [private]
Definition at line 34 of file MainView.java.
Referenced by ScheatorView.MainView.initComponents().
javax.swing.JPanel ScheatorView.MainView.statusPanel [private]
Definition at line 35 of file MainView.java.
Referenced by ScheatorView.MainView.initComponents().
The documentation for this class was generated from the following file:
src/ScheatorView/MainView.java