Scheator: ScheatorView.MainTablePanel Class Reference
ScheatorView.MainTablePanel Class Reference
Classes
class ButtonListener
Public Member Functions
MainTablePanel (MainController controller)
void setTableEdited (Boolean tableEdited)
Boolean isTableEdited ()
void print ()
void save ()
void moveUp ()
void moveDown ()
void comboBoxEvent (ListDataEvent e)
void mainTableChanged (TableModelEvent e)
void itemStateChanged (ItemEvent e)
Public Attributes
Boolean tableEdited = false
Package Attributes
JTable mainTable
javax.swing.JButton upButton = new javax.swing.JButton()
javax.swing.JButton downButton = new javax.swing.JButton()
javax.swing.JButton saveButton = new javax.swing.JButton()
MainTableModel mainTableModel
Private Member Functions
void init ()
JTable initTable (JTable table)
Private Attributes
org.jdesktop.application.ResourceMap resourceMap
javax.swing.ActionMap actionMap
MainController controller
Detailed Description
Author:
mep
Definition at line 24 of file MainTablePanel.java.
Constructor & Destructor Documentation
ScheatorView.MainTablePanel.MainTablePanel (MainController controller)
Definition at line 36 of file MainTablePanel.java.
References ScheatorController.AbstractController.addView(), and ScheatorView.MainTablePanel.init().
{
        this.controller = controller;
        controller.addView(this);
        init();
    }
Member Function Documentation
void ScheatorView.MainTablePanel.comboBoxEvent (ListDataEvent e)
Reimplemented from ScheatorView.AbstractView.
Definition at line 178 of file MainTablePanel.java.
{
        String source = e.getSource().getClass().getName();
        System.err.println("comboBoxEvent source: " + source);
    }
void ScheatorView.MainTablePanel.init () [private]
Definition at line 55 of file MainTablePanel.java.
References ScheatorView.MainTablePanel.actionMap, ScheatorView.MainTablePanel.controller, ScheatorView.MainTablePanel.downButton, ScheatorView.MainTablePanel.initTable(), ScheatorView.MainTablePanel.mainTable, ScheatorView.MainTablePanel.mainTableModel, ScheatorView.MainTablePanel.resourceMap, ScheatorView.MainTablePanel.saveButton, and ScheatorView.MainTablePanel.upButton.
Referenced by ScheatorView.MainTablePanel.MainTablePanel().
{
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        this.resourceMap = org.jdesktop.application.Application.getInstance(scheator.ScheatorApp.class).getContext().getResourceMap(MainTablePanel.class);
        this.actionMap = org.jdesktop.application.Application.getInstance(scheator.ScheatorApp.class).getContext().getActionMap(MainTablePanel.class, this);
        mainTableModel = new MainTableModel(controller);
        mainTable = new JTable(mainTableModel);
        initTable(mainTable);
        mainTable.setFillsViewportHeight(true);
        JScrollPane scrollPanel = new JScrollPane(mainTable);
        panel.setLayout(new BoxLayout(panel, BoxLayout.X_AXIS));
        buttonPanel.setLayout(new BoxLayout(buttonPanel, BoxLayout.Y_AXIS));
        upButton.setText(resourceMap.getString("moveUp.text"));
        upButton.setName("moveUp");
        upButton.setAction(actionMap.get("moveUp"));
        upButton.addActionListener(new ButtonListener());
        downButton.setText(resourceMap.getString("moveDown.text"));
        downButton.setName("moveDown");
        downButton.setAction(actionMap.get("moveDown"));
        downButton.addActionListener(new ButtonListener());
        saveButton.setText(resourceMap.getString("save.text"));
        saveButton.setName("save");
        saveButton.setAction(actionMap.get("save")); // NOI18N
        buttonPanel.add(upButton);
        buttonPanel.add(downButton);
        buttonPanel.add(saveButton);
        add(scrollPanel);
        add(buttonPanel, BorderLayout.NORTH);
        add(panel);
        setName("tablePane");
    }
JTable ScheatorView.MainTablePanel.initTable (JTable table) [private]
Definition at line 97 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.init().
{
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.setColumnSelectionAllowed(false);
        table.setRowSelectionAllowed(true);
        table.setFillsViewportHeight(true);
        table.setDragEnabled(true);
        table.setShowVerticalLines(false);
        table.getColumnModel().getColumn(0).setPreferredWidth(5);
        table.getColumnModel().getColumn(1).setPreferredWidth(100);
        table.getColumnModel().getColumn(2).setPreferredWidth(100);
        return table;
    }
Boolean ScheatorView.MainTablePanel.isTableEdited ()
Definition at line 50 of file MainTablePanel.java.
References ScheatorView.MainTablePanel.tableEdited.
{
        return tableEdited;
    }
void ScheatorView.AbstractView.itemStateChanged (ItemEvent e) [inherited]
Reimplemented in ScheatorView.MainSearchPanel.
Definition at line 28 of file AbstractView.java.
{
        // By default, do nothing
    }
void ScheatorView.AbstractView.mainTableChanged (TableModelEvent e) [inherited]
Definition at line 24 of file AbstractView.java.
{
        // By default, do nothing
    }
void ScheatorView.MainTablePanel.moveDown ()
Definition at line 144 of file MainTablePanel.java.
References ScheatorView.MainTablePanel.controller, ScheatorView.MainTablePanel.mainTable, ScheatorController.MainController.moveMatch(), and ScheatorView.MainTablePanel.setTableEdited().
{
        Integer row = mainTable.getSelectedRow();
        if (row < mainTable.getRowCount()-1) {
            controller.moveMatch(row, row + 1);
            setTableEdited(true);
        }
}
void ScheatorView.MainTablePanel.moveUp ()
Definition at line 135 of file MainTablePanel.java.
References ScheatorView.MainTablePanel.controller, ScheatorView.MainTablePanel.mainTable, ScheatorController.MainController.moveMatch(), and ScheatorView.MainTablePanel.setTableEdited().
{
        Integer row = mainTable.getSelectedRow();
        if (row > 0) {
            controller.moveMatch(row, row - 1);
            setTableEdited(true);
        }
    }
void ScheatorView.MainTablePanel.print ()
A very basic printing facility.
Printing is done here becaus the table component supports direct printing.
Todo:
Add more sophisticated printing by returning a Printable object from this class to a caller.
Definition at line 120 of file MainTablePanel.java.
References ScheatorView.MainTablePanel.mainTable.
{
        try {
            mainTable.print();
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }
void ScheatorView.MainTablePanel.save ()
Definition at line 129 of file MainTablePanel.java.
References ScheatorView.MainTablePanel.controller, ScheatorController.MainController.scheduleEdited(), and ScheatorView.MainTablePanel.setTableEdited().
                       {
        controller.scheduleEdited();
        setTableEdited(false);
    }
void ScheatorView.MainTablePanel.setTableEdited (Boolean tableEdited)
Definition at line 44 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.ButtonListener.actionPerformed(), ScheatorView.MainTablePanel.moveDown(), ScheatorView.MainTablePanel.moveUp(), and ScheatorView.MainTablePanel.save().
{
        Boolean oldValue = tableEdited;
        this.tableEdited = tableEdited;
        firePropertyChange("tableEdited", oldValue, this.tableEdited);
    }
Member Data Documentation
javax.swing.ActionMap ScheatorView.MainTablePanel.actionMap [private]
Definition at line 31 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.init().
MainController ScheatorView.MainTablePanel.controller [private]
Definition at line 32 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.init(), ScheatorView.MainTablePanel.moveDown(), ScheatorView.MainTablePanel.moveUp(), and ScheatorView.MainTablePanel.save().
javax.swing.JButton ScheatorView.MainTablePanel.downButton = new javax.swing.JButton() [package]
Definition at line 28 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.init().
JTable ScheatorView.MainTablePanel.mainTable [package]
Definition at line 26 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.ButtonListener.actionPerformed(), ScheatorView.MainTablePanel.init(), ScheatorView.MainTablePanel.moveDown(), ScheatorView.MainTablePanel.moveUp(), and ScheatorView.MainTablePanel.print().
MainTableModel ScheatorView.MainTablePanel.mainTableModel [package]
Definition at line 34 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.ButtonListener.actionPerformed(), and ScheatorView.MainTablePanel.init().
org.jdesktop.application.ResourceMap ScheatorView.MainTablePanel.resourceMap [private]
Definition at line 30 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.init().
javax.swing.JButton ScheatorView.MainTablePanel.saveButton = new javax.swing.JButton() [package]
Definition at line 29 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.init().
Boolean ScheatorView.MainTablePanel.tableEdited = false
Definition at line 33 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.isTableEdited().
javax.swing.JButton ScheatorView.MainTablePanel.upButton = new javax.swing.JButton() [package]
Definition at line 27 of file MainTablePanel.java.
Referenced by ScheatorView.MainTablePanel.init().
The documentation for this class was generated from the following file:
src/ScheatorView/MainTablePanel.java