Scheator: ScheatorController.AbstractController.ListDataListenerImpl Class Reference
ScheatorController.AbstractController.ListDataListenerImpl Class Reference
Public Member Functions
void contentsChanged (ListDataEvent e)
void intervalRemoved (ListDataEvent e)
void intervalAdded (ListDataEvent e)
Detailed Description
Definition at line 109 of file AbstractController.java.
Member Function Documentation
void ScheatorController.AbstractController.ListDataListenerImpl.contentsChanged (ListDataEvent e)
Definition at line 110 of file AbstractController.java.
References ScheatorView.MainView.comboBoxEvent(), ScheatorController.AbstractController.mainFrame, and ScheatorController.AbstractController.registeredViews.
{
            for (AbstractView view: registeredViews) {
                view.comboBoxEvent(e);
            }
            System.err.println("contentsChanged()");
            mainFrame.comboBoxEvent(e);
        }
void ScheatorController.AbstractController.ListDataListenerImpl.intervalAdded (ListDataEvent e)
Definition at line 125 of file AbstractController.java.
References ScheatorView.MainView.comboBoxEvent(), ScheatorController.AbstractController.mainFrame, and ScheatorController.AbstractController.registeredViews.
{
            for (AbstractView view: registeredViews) {
                view.comboBoxEvent(e);
            }
            mainFrame.comboBoxEvent(e);
        }
void ScheatorController.AbstractController.ListDataListenerImpl.intervalRemoved (ListDataEvent e)
Definition at line 118 of file AbstractController.java.
References ScheatorView.MainView.comboBoxEvent(), ScheatorController.AbstractController.mainFrame, and ScheatorController.AbstractController.registeredViews.
{
            for (AbstractView view: registeredViews) {
                view.comboBoxEvent(e);
            }
            mainFrame.comboBoxEvent(e);
        }
The documentation for this class was generated from the following file:
src/ScheatorController/AbstractController.java