Scheator: scheator.MainTablePane Class Reference
scheator.MainTablePane Class Reference
Public Member Functions
MainTablePane (org.jdesktop.application.ResourceMap resourceMap, javax.swing.ActionMap actionMap)
void print ()
void save ()
void moveUp ()
void moveDown ()
Package Attributes
JTable mainTable
javax.swing.JButton upButton = new javax.swing.JButton()
javax.swing.JButton downButton = new javax.swing.JButton()
javax.swing.JButton saveButton = new javax.swing.JButton()
Private Member Functions
void initTable ()
Private Attributes
org.jdesktop.application.ResourceMap resources
Detailed Description
Author:
mep
Definition at line 15 of file MainTablePane.java.
Constructor & Destructor Documentation
scheator.MainTablePane.MainTablePane (org.jdesktop.application.ResourceMap resourceMap, javax.swing.ActionMap actionMap)
Definition at line 23 of file MainTablePane.java.
References scheator.MainTablePane.downButton, scheator.MainTablePane.initTable(), scheator.MainTablePane.mainTable, scheator.MainTablePane.resources, scheator.MainTablePane.saveButton, and scheator.MainTablePane.upButton.
{
            resources = resourceMap;
            String[] columnNames = {"Round", "Home", "Away"};
//            columnNames[0] = resourceMap.getString("ColRound");
  //          columnNames[1] = resourceMap.getString("ColHome");
    //        columnNames[2] = resourceMap.getString("ColAway");
            Object[][] data = {{"aaa", "bbb", "ccc"}, {"111", "222", "333"}, {"xxx", "yyy", "zzz"}};
            javax.swing.JPanel panel = new javax.swing.JPanel();
            javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
            mainTable = new JTable(data, columnNames);
            initTable();
            mainTable.setFillsViewportHeight(true);
            JScrollPane scrollPanel = new JScrollPane(mainTable);
            panel.setLayout(new BoxLayout(panel, BoxLayout.X_AXIS));
            buttonPanel.setLayout(new BoxLayout(buttonPanel, BoxLayout.Y_AXIS));
            upButton.setAction(actionMap.get("moveUp"));
            upButton.setText(resourceMap.getString("upButton.text"));
            upButton.setName("upButton");
            downButton.setAction(actionMap.get("moveDown"));
            downButton.setText(resourceMap.getString("downButton.text"));
            downButton.setName("downButton");
            saveButton.setAction(actionMap.get("save")); // NOI18N
            saveButton.setText(resourceMap.getString("saveButton.text"));
            saveButton.setName("saveButton");
            buttonPanel.add(upButton);
            buttonPanel.add(downButton);
            buttonPanel.add(saveButton);
            panel.add(scrollPanel);
            panel.add(buttonPanel, BorderLayout.NORTH);
            add(panel);
            setName("tablePane");
            setViewportView(panel);
        }
Member Function Documentation
void scheator.MainTablePane.initTable () [private]
Definition at line 71 of file MainTablePane.java.
References scheator.MainTablePane.mainTable.
Referenced by scheator.MainTablePane.MainTablePane().
{
            javax.swing.table.TableColumn column = null;
            mainTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            mainTable.setColumnSelectionAllowed(false);
            mainTable.setRowSelectionAllowed(true);
            mainTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            mainTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            mainTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        }
void scheator.MainTablePane.moveDown ()
Definition at line 110 of file MainTablePane.java.
{
        }
void scheator.MainTablePane.moveUp ()
Definition at line 105 of file MainTablePane.java.
{
         //   if (mainTable.)
        }
void scheator.MainTablePane.print ()
A very basic printing facility.
Printing is done here becaus the table component supports direct printing.
Todo:
Add more sophisticated printing by returning a Printable obejct from this class to a caller.
Definition at line 91 of file MainTablePane.java.
References scheator.MainTablePane.mainTable.
{
            try {
                mainTable.print();
            } catch (java.awt.print.PrinterException e) {
                System.err.format("Cannot print %s%n", e.getMessage());
            }
        }
void scheator.MainTablePane.save ()
Definition at line 100 of file MainTablePane.java.
{
        }
Member Data Documentation
javax.swing.JButton scheator.MainTablePane.downButton = new javax.swing.JButton() [package]
Definition at line 19 of file MainTablePane.java.
Referenced by scheator.MainTablePane.MainTablePane().
JTable scheator.MainTablePane.mainTable [package]
Definition at line 17 of file MainTablePane.java.
Referenced by scheator.MainTablePane.initTable(), scheator.MainTablePane.MainTablePane(), and scheator.MainTablePane.print().
org.jdesktop.application.ResourceMap scheator.MainTablePane.resources [private]
Definition at line 21 of file MainTablePane.java.
Referenced by scheator.MainTablePane.MainTablePane().
javax.swing.JButton scheator.MainTablePane.saveButton = new javax.swing.JButton() [package]
Definition at line 20 of file MainTablePane.java.
Referenced by scheator.MainTablePane.MainTablePane().
javax.swing.JButton scheator.MainTablePane.upButton = new javax.swing.JButton() [package]
Definition at line 18 of file MainTablePane.java.
Referenced by scheator.MainTablePane.MainTablePane().
The documentation for this class was generated from the following file:
src/scheator/MainTablePane.java