Scheator: ScheatorController.AbstractController Class Reference
ScheatorController.AbstractController Class Reference
Public Member Functions
AbstractController ()
void addModel (AbstractModel model)
void removeModel (AbstractModel model)
void addView (AbstractViewPanel view)
void removeView (AbstractViewPanel view)
void addMainFrame (MainView frame)
void propertyChange (PropertyChangeEvent evt)
Protected Member Functions
void setModelProperty (String propertyName, Object newValue)
Private Attributes
ArrayList< AbstractViewPanel > registeredViews
MainView mainFrame
ArrayList< AbstractModel > registeredModels
Detailed Description
This class provides base level functionality for each controller. This includes the ability to register multiple models and views, propogating model change events to each of the views, and providing a utility function to broadcast model property changes when necessary.
Author:
Robert Eckstein
Definition at line 27 of file AbstractController.java.
Constructor & Destructor Documentation
ScheatorController.AbstractController.AbstractController ()
Creates a new instance of Controller
Definition at line 37 of file AbstractController.java.
References ScheatorController.AbstractController.registeredModels, and ScheatorController.AbstractController.registeredViews.
{
        registeredViews = new ArrayList<AbstractViewPanel>();
        registeredModels = new ArrayList<AbstractModel>();
    }
Member Function Documentation
void ScheatorController.AbstractController.addMainFrame (MainView frame)
Definition at line 82 of file AbstractController.java.
References ScheatorController.AbstractController.mainFrame.
Referenced by ScheatorView.MainView.MainView().
{
        this.mainFrame = frame;
    }
void ScheatorController.AbstractController.addModel (AbstractModel model)
Binds a model to this controller. Once added, the controller will listen for all model property changes and propogate them on to registered views. In addition, it is also responsible for resetting the model properties when a view changes state.
Parameters:
model The model to be added
Definition at line 50 of file AbstractController.java.
References ScheatorController.AbstractController.registeredModels.
{
        registeredModels.add(model);
        //model.addEventListener(this);
    }
void ScheatorController.AbstractController.addView (AbstractViewPanel view)
Binds a view to this controller. The controller will propogate all model property changes to each view for consideration.
Parameters:
view The view to be added
Definition at line 70 of file AbstractController.java.
References ScheatorController.AbstractController.registeredViews.
Referenced by ScheatorView.MainView.initComponents(), ScheatorView.MainSearchPanel.MainSearchPanel(), and ScheatorView.MainTablePanel.MainTablePanel().
{
        registeredViews.add(view);
    }
void ScheatorController.AbstractController.propertyChange (PropertyChangeEvent evt)
This method is used to implement the PropertyChangeListener interface. Any model changes will be sent to this controller through the use of this method.
Parameters:
evt An object that describes the model's property change.
Definition at line 94 of file AbstractController.java.
References ScheatorController.AbstractController.mainFrame, ScheatorView.MainView.modelPropertyChange(), and ScheatorController.AbstractController.registeredViews.
{
        for (AbstractViewPanel view: registeredViews) {
            view.modelPropertyChange(evt);
        }
        mainFrame.modelPropertyChange(evt);
    }
void ScheatorController.AbstractController.removeModel (AbstractModel model)
Unbinds a model from this controller.
Parameters:
model The model to be removed
Definition at line 59 of file AbstractController.java.
References ScheatorController.AbstractController.registeredModels.
{
        registeredModels.remove(model);
        //model.removePropertyChangeListener(this);
    }
void ScheatorController.AbstractController.removeView (AbstractViewPanel view)
Unbinds a view from this controller.
Parameters:
view The view to be removed
Definition at line 78 of file AbstractController.java.
References ScheatorController.AbstractController.registeredViews.
{
        registeredViews.remove(view);
    }
void ScheatorController.AbstractController.setModelProperty (String propertyName, Object newValue) [protected]
Convienence method that subclasses can call upon to fire off property changes back to the models. This method used reflection to inspect each of the model classes to determine if it is the owner of the property in question. If it isn't, a NoSuchMethodException is throws (which the method ignores).
Parameters:
propertyName The name of the property
newValue An object that represents the new value of the property.
Definition at line 112 of file AbstractController.java.
References ScheatorController.AbstractController.registeredModels.
{
        for (AbstractModel model: registeredModels) {
            try {
                Method method = model.getClass().
                    getMethod("set"+propertyName, new Class[] {
                                                      newValue.getClass()
                                                  }
                             );
                method.invoke(model, newValue);
            } catch (Exception ex) {
                //  Handle exception
            }
        }
    }
Member Data Documentation
MainView ScheatorController.AbstractController.mainFrame [private]
Definition at line 32 of file AbstractController.java.
Referenced by ScheatorController.AbstractController.addMainFrame(), and ScheatorController.AbstractController.propertyChange().
ArrayList<AbstractModel> ScheatorController.AbstractController.registeredModels [private]
Definition at line 33 of file AbstractController.java.
Referenced by ScheatorController.AbstractController.AbstractController(), ScheatorController.AbstractController.addModel(), ScheatorController.AbstractController.removeModel(), and ScheatorController.AbstractController.setModelProperty().
ArrayList<AbstractViewPanel> ScheatorController.AbstractController.registeredViews [private]
Definition at line 31 of file AbstractController.java.
Referenced by ScheatorController.AbstractController.AbstractController(), ScheatorController.AbstractController.addView(), ScheatorController.AbstractController.propertyChange(), and ScheatorController.AbstractController.removeView().
The documentation for this class was generated from the following file:
src/ScheatorController/AbstractController.java