Scheator: ScheatorView.MainSearchPanel Class Reference
ScheatorView.MainSearchPanel Class Reference
Classes
class ComboBoxListener
Public Member Functions
MainSearchPanel (MainController controller)
void setSearchEnabled (boolean searchEnabled)
Boolean isSearchEnabled ()
void search ()
void seriesList ()
void seasonList ()
void itemStateChanged (ItemEvent e)
void comboBoxEvent (ListDataEvent e)
void mainTableChanged (TableModelEvent e)
Package Attributes
JComboBox seriesList
JComboBox seasonList
JButton searchButton = new JButton()
SeriesComboBoxModel seriesModel
SeasonComboBoxModel seasonModel
Private Attributes
MainController controller
org.jdesktop.application.ResourceMap resourceMap
javax.swing.ActionMap actionMap
boolean searchEnabled = false
Detailed Description
Author:
mep
Definition at line 20 of file MainSearchPanel.java.
Constructor & Destructor Documentation
ScheatorView.MainSearchPanel.MainSearchPanel (MainController controller)
Definition at line 32 of file MainSearchPanel.java.
References ScheatorView.MainSearchPanel.actionMap, ScheatorController.AbstractController.addView(), ScheatorView.MainSearchPanel.resourceMap, ScheatorView.MainSearchPanel.searchButton, ScheatorView.MainSearchPanel.seasonList(), ScheatorView.MainSearchPanel.seasonModel, ScheatorView.MainSearchPanel.seriesList(), and ScheatorView.MainSearchPanel.seriesModel.
{
        this.controller = controller;
        controller.addView(this);
        String[] seriesNames = {"SM-liiga", "Veikkausliiga", "Valioliiga"};
        String[] seasonNames = {"2008-09", "2009-10"};
        this.resourceMap = org.jdesktop.application.Application.getInstance(scheator.ScheatorApp.class).getContext().getResourceMap(MainSearchPanel.class);
        this.actionMap = org.jdesktop.application.Application.getInstance(scheator.ScheatorApp.class).getContext().getActionMap(MainSearchPanel.class, this);
        javax.swing.JPanel panel = new javax.swing.JPanel();
        JLabel seriesLabel = new JLabel();
        JLabel seasonLabel = new JLabel();
        seriesModel = new SeriesComboBoxModel(controller);
        seriesList = new JComboBox(seriesModel);
        seriesList.setPrototypeDisplayValue("XXXXXXXXXXXX");
        seriesList.setName("series");
        seriesList.setAction(actionMap.get("seriesList"));
        seriesList.setEditable(false);
//        seriesList.addItemListener(new ComboBoxListener());
        seasonModel = new SeasonComboBoxModel(controller);
        seasonList = new JComboBox(seasonModel);
        seasonList.setPrototypeDisplayValue("XXXXXXXXXXXX");
        seasonList.setName("season");
        seasonList.setAction(actionMap.get("seasonList"));
        seasonList.setEditable(false);
//        seasonList.addItemListener(new ComboBoxListener());
        searchButton = new JButton();
        //searchButton.setSize(10, 10);
        searchButton.setAction(actionMap.get("search"));
        seriesLabel.setText(resourceMap.getString("seriesLabel.text"));
        seasonLabel.setText(resourceMap.getString("seasonLabel.text"));
        searchButton.setText(resourceMap.getString("searchButton.Action.text"));
        add(seriesLabel);
        add(seriesList);
        add(seasonLabel);
        add(seasonList);
        add(searchButton);
        setName("searchPane");
    }
Member Function Documentation
void ScheatorView.AbstractView.comboBoxEvent (ListDataEvent e) [inherited]
Reimplemented in ScheatorView.MainTablePanel.
Definition at line 20 of file AbstractView.java.
{
        // By default, do nothing
    }
Boolean ScheatorView.MainSearchPanel.isSearchEnabled ()
Definition at line 87 of file MainSearchPanel.java.
References ScheatorView.MainSearchPanel.searchEnabled.
{
        return searchEnabled;
    }
void ScheatorView.MainSearchPanel.itemStateChanged (ItemEvent e)
Reimplemented from ScheatorView.AbstractView.
Definition at line 119 of file MainSearchPanel.java.
{
        Object source = e.getItem().getClass().getName();
        if (e.getStateChange() == ItemEvent.SELECTED) {
        }
        System.err.println("itemStateChanged source: " + source);
    }
void ScheatorView.AbstractView.mainTableChanged (TableModelEvent e) [inherited]
Definition at line 24 of file AbstractView.java.
{
        // By default, do nothing
    }
void ScheatorView.MainSearchPanel.search ()
Definition at line 92 of file MainSearchPanel.java.
References ScheatorView.MainSearchPanel.controller, ScheatorController.MainController.searchMainTable(), and ScheatorView.MainSearchPanel.seasonList().
{
        System.err.println("Searching");
        ScheatorDb.DbObject.Data data = (ScheatorDb.DbObject.Data) seasonList.getSelectedItem();
        Integer seasonId = (Integer) data.get("id");
        controller.searchMainTable(seasonId);
    }
void ScheatorView.MainSearchPanel.seasonList ()
Definition at line 109 of file MainSearchPanel.java.
References ScheatorModel.ScheatorComboBoxModel.getSelectedItem(), ScheatorView.MainSearchPanel.seasonModel, and ScheatorView.MainSearchPanel.setSearchEnabled().
Referenced by ScheatorView.MainSearchPanel.MainSearchPanel(), and ScheatorView.MainSearchPanel.search().
{
        if ((Season.Data)seasonModel.getSelectedItem() != null) {
            setSearchEnabled(true);
            System.err.println("SELECTED");
        } else {
            setSearchEnabled(false);
        }
    }
void ScheatorView.MainSearchPanel.seriesList ()
Definition at line 100 of file MainSearchPanel.java.
References ScheatorModel.ScheatorComboBoxModel.getSelectedItem(), ScheatorView.MainSearchPanel.seasonModel, ScheatorView.MainSearchPanel.seriesModel, and ScheatorModel.SeasonComboBoxModel.update().
Referenced by ScheatorView.MainSearchPanel.MainSearchPanel().
{
        //seasonModel.fill(seriesList.getSelectedId());
        //controller.seriesSelected(seriesList.getSelectedIndex());
        Series.Data selected = (Series.Data)seriesModel.getSelectedItem();
        Integer id = (Integer) selected.get("id");
        seasonModel.update(id);
    }
void ScheatorView.MainSearchPanel.setSearchEnabled (boolean searchEnabled)
Definition at line 81 of file MainSearchPanel.java.
Referenced by ScheatorView.MainSearchPanel.seasonList().
{
        boolean oldValue = this.searchEnabled;
        this.searchEnabled = searchEnabled;
        firePropertyChange("searchEnabled", oldValue, this.searchEnabled);
    }
Member Data Documentation
javax.swing.ActionMap ScheatorView.MainSearchPanel.actionMap [private]
Definition at line 24 of file MainSearchPanel.java.
Referenced by ScheatorView.MainSearchPanel.MainSearchPanel().
MainController ScheatorView.MainSearchPanel.controller [private]
Definition at line 22 of file MainSearchPanel.java.
Referenced by ScheatorView.MainSearchPanel.search().
org.jdesktop.application.ResourceMap ScheatorView.MainSearchPanel.resourceMap [private]
Definition at line 23 of file MainSearchPanel.java.
Referenced by ScheatorView.MainSearchPanel.MainSearchPanel().
JButton ScheatorView.MainSearchPanel.searchButton = new JButton() [package]
Definition at line 27 of file MainSearchPanel.java.
Referenced by ScheatorView.MainSearchPanel.MainSearchPanel().
boolean ScheatorView.MainSearchPanel.searchEnabled = false [private]
Definition at line 30 of file MainSearchPanel.java.
Referenced by ScheatorView.MainSearchPanel.isSearchEnabled().
JComboBox ScheatorView.MainSearchPanel.seasonList [package]
Definition at line 26 of file MainSearchPanel.java.
SeasonComboBoxModel ScheatorView.MainSearchPanel.seasonModel [package]
Definition at line 29 of file MainSearchPanel.java.
Referenced by ScheatorView.MainSearchPanel.MainSearchPanel(), ScheatorView.MainSearchPanel.seasonList(), and ScheatorView.MainSearchPanel.seriesList().
JComboBox ScheatorView.MainSearchPanel.seriesList [package]
Definition at line 25 of file MainSearchPanel.java.
SeriesComboBoxModel ScheatorView.MainSearchPanel.seriesModel [package]
Definition at line 28 of file MainSearchPanel.java.
Referenced by ScheatorView.MainSearchPanel.MainSearchPanel(), and ScheatorView.MainSearchPanel.seriesList().
The documentation for this class was generated from the following file:
src/ScheatorView/MainSearchPanel.java